In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({
    "age": [25, 32, np.nan, 45, 29, 38, 51, np.nan, 27, 40],
    "income": [50000, 62000, 58000, np.nan, 52000, 75000, 90000, 61000, np.nan, 70000],
    "city": ["NY", "MD", "MD", "VA", np.nan, "NY", "VA", "MD", "NY", "VA"],
    "owns_house": ["No", "Yes", "No", "Yes", "No", np.nan, "Yes", "No", "No", "Yes"],
    "purchased": [0, 1, 0, 1, 0, 1, 1, 0, 0, 1]
})

df

    age   income city owns_house  purchased
0  25.0  50000.0   NY         No          0
1  32.0  62000.0   MD        Yes          1
2   NaN  58000.0   MD         No          0
3  45.0      NaN   VA        Yes          1
4  29.0  52000.0  NaN         No          0
5  38.0  75000.0   NY        NaN          1
6  51.0  90000.0   VA        Yes          1
7   NaN  61000.0   MD         No          0
8  27.0      NaN   NY         No          0
9  40.0  70000.0   VA        Yes          1

In [3]:
df.head()

    age   income city owns_house  purchased
0  25.0  50000.0   NY         No          0
1  32.0  62000.0   MD        Yes          1
2   NaN  58000.0   MD         No          0
3  45.0      NaN   VA        Yes          1
4  29.0  52000.0  NaN         No          0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         8 non-null      float64
 1   income      8 non-null      float64
 2   city        9 non-null      str
 3   owns_house  9 non-null      str
 4   purchased   10 non-null     int64
dtypes: float64(2), int64(1), str(2)
memory usage: 532.0 bytes

In [6]:
df.isna().sum() # shows the number of missing values in each column

age           2
income        2
city          1
owns_house    1
purchased     0
dtype: int64

In [7]:
X = df.drop(columns='purchased')
y = df['purchased']

In [10]:
X # features

    age   income city owns_house
0  25.0  50000.0   NY         No
1  32.0  62000.0   MD        Yes
2   NaN  58000.0   MD         No
3  45.0      NaN   VA        Yes
4  29.0  52000.0  NaN         No
5  38.0  75000.0   NY        NaN
6  51.0  90000.0   VA        Yes
7   NaN  61000.0   MD         No
8  27.0      NaN   NY         No
9  40.0  70000.0   VA        Yes

In [11]:
y # target

0    0
1    1
2    0
3    1
4    0
5    1
6    1
7    0
8    0
9    1
Name: purchased, dtype: int64

In [12]:
numeric_features = ['age', 'income']
categorical_features = ['city', 'owns_house']

In [16]:
from sklearn.model_selection import train_test_split

# preprocessing should be fitted only on the training data to prevent data leakage.
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [14]:
X_train

    age   income city owns_house
6  51.0  90000.0   VA        Yes
8  27.0      NaN   NY         No
2   NaN  58000.0   MD         No
0  25.0  50000.0   NY         No
3  45.0      NaN   VA        Yes
1  32.0  62000.0   MD        Yes
5  38.0  75000.0   NY        NaN
4  29.0  52000.0  NaN         No

In [15]:
X_test

    age   income city owns_house
7   NaN  61000.0   MD         No
9  40.0  70000.0   VA        Yes

In [17]:
from sklearn.impute import SimpleImputer

In [26]:
numeric_imputer = SimpleImputer(strategy='median') # when there are outliers, it's safer to use median.

In [19]:
numeric_imputer.fit(X_train[numeric_features])

SimpleImputer(strategy='median')

In [21]:
np.set_printoptions(suppress=True, precision=4)

numeric_imputer.statistics_

array([   32., 60000.])

In [22]:
X_train_numeric = numeric_imputer.transform(
    X_train[numeric_features]
)

In [23]:
X_train_numeric

array([[   51., 90000.],
       [   27., 60000.],
       [   32., 58000.],
       [   25., 50000.],
       [   45., 60000.],
       [   32., 62000.],
       [   38., 75000.],
       [   29., 52000.]])

In [24]:
numeric_imputer.fit_transform(
    X_train[numeric_features]
)

array([[   51., 90000.],
       [   27., 60000.],
       [   32., 58000.],
       [   25., 50000.],
       [   45., 60000.],
       [   32., 62000.],
       [   38., 75000.],
       [   29., 52000.]])

In [25]:
# We want to apply the median we got from X_train to X_test (no separate fitting)
X_test_numeric = numeric_imputer.transform(
    X_test[numeric_features]
)

X_test_numeric

array([[   32., 61000.],
       [   40., 70000.]])

* TRAIN: fit + transform
* TEST: transform only

In [27]:
X_train[categorical_features]

  city owns_house
6   VA        Yes
8   NY         No
2   MD         No
0   NY         No
3   VA        Yes
1   MD        Yes
5   NY        NaN
4  NaN         No

In [28]:
categorical_imputer = SimpleImputer(
    strategy='most_frequent'
)

In [29]:
X_train_categorical = categorical_imputer.fit_transform(
    X_train[categorical_features]
)

X_train_categorical

array([['VA', 'Yes'],
       ['NY', 'No'],
       ['MD', 'No'],
       ['NY', 'No'],
       ['VA', 'Yes'],
       ['MD', 'Yes'],
       ['NY', 'No'],
       ['NY', 'No']], dtype=object)

In [30]:
# if we just give numbers to the values under one column, the computer might think one is bigger than others, 
# so that's why we need one-hot-endcoding.
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(
    handle_unknown='ignore' # Ignore unseen categories in new/test data instead of raising an error
)

encoded_train = encoder.fit_transform(
    X_train_categorical
)

encoded_train.toarray()

array([[0., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 0., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 0., 1., 0., 1.],
       [1., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0.]])

In [31]:
encoder.get_feature_names_out(categorical_features)

array(['city_MD', 'city_NY', 'city_VA', 'owns_house_No', 'owns_house_Yes'],
      dtype=object)

In [32]:
X_test_categorical = categorical_imputer.transform(
    X_test[categorical_features]
)

encoded_test = encoder.transform(
    X_test_categorical
)

encoded_test.toarray()

array([[1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 1.]])

* TRAIN
    * imputer.fit_transform()
    * encoder.fit_transform()

* TEST
    * imputer.transform()
    * encoder.transform()

1. What is a missing value? - A missing value is a value that is absent or not recorded in a dataset.

2. What does SimpleImputer do? - SimpleImputer fills missing values using a strategy such as the mean, median, or most frequent value.

3. Why might we use the median instead of the mean? - We might use the median instead of the mean because the median is less affected by outliers.

4. What does OneHotEncoder do? - OneHotEncoder transforms categorical columns into numerical binary columns so that machine learning models can use them.

5. Why should we fit preprocessing steps only on the training data? - We should fit preprocessing steps only on the training data to prevent data leakage from the test set.

6. What is the difference between fit() and transform()? - fit() learns information from the data, while transform() uses that learned information to modify the data.

7. Why do we use handle_unknown="ignore"? - We use handle_unknown="ignore" to avoid an error when the test data contains a new category that was not seen during training.